inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Exclude:
    - "spec/**/*"
    - "test/**/*"
    - "lib/uddf/**/*"
